name: oto_service
description: "Application mobile O'TO - Service de garage à domicile"
publish_to: 'none' # Ce projet n'est pas publié sur pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Interface & Design
  cupertino_icons: ^1.0.6
  intl_phone_field: ^3.0.1

  # Firebase
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.17.2

  # URL launcher (ajouté pour appel/téléchargement/sms/mail)
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700
